### PR TITLE
IBX-5421: Handled deleted content in image asset field type

### PR DESCRIPTION
**Pull request by barw4**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-5421](https://issues.ibexa.co/browse/IBX-5421)
| **Type**| bug
| **Target version** | `v3.3`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

As the title states.

### CODE REVIEW

**Comment by ViniTou** [comment]
Shouldn't those relations be deleted as well when the content in question in moved to trash? That's what normally happens, right? What is the difference here?

**Comment by barw4** [comment]
@ViniTou I don't think we should delete relations when something is put into the trash. In such cases, we are giving a message that content is deleted in UI (or not accessible), aside from that it can be always recovered so it looks like it's properly handled.  Deleting those would make this functionality obsolete.

**Comment by ViniTou** [comment]
@barw4 
> I don't think we should delete relations when something is put into the trash. 

True, but in reproduction step we are talking about removing item completely, and `\Ibexa\Core\Persistence\Legacy\Content\Location\Trash\Handler::deleteTrashItem` calls `delete` on content handler which should clear relations as well. 

I may misunderstand the flow described in ticket then, if the problem is with sendin to trash and not about removing from it.

**Comment by barw4** [comment]
@ViniTou it's actually about removing them completely. I'll take a look at this again, as indeed, removing TrashItem should clear relations.

**Comment by barw4** [comment]
Seems like `data_text` is not properly removed in Image Asset fieldtype, it works for relations properly, closing this as PR will be done for kernel.

**Comment by barw4** [comment]
Actually, I think we should leave this PR with changes only to ImageAsset, otherwise, we would have to provide a script clearing orphaned records in the `ezcontentobject_attribute` table.

**Comment by ViniTou** [comment]
Can we at least add logging here then, as it should not happen and if this fails it means that your DB _should_ be somehow fixed?

**Comment by barw4** [comment]
@ViniTou I'm not sure logging will be necessary. Do we really want to log that there are some leftovers from `ezcontentobject_attribute` that will be updated during the saving of current content with really any data? After saving content a "corruption" will be gone. Logging it will give developer a clue that there is something wrong going on with a database but at this point in time this issue will resolve itself in most cases and he wouldn't be able to find a problem.

**Comment by barw4** [comment]
After some further investigation, I still stand by my current solution. This is the simplest one and won't cause any BC. Perhaps we should do something like here https://github.com/ezsystems/ezplatform-kernel/blob/1.3/eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php#L1146-L1154, but this would be painful as we would have to provide empty values taking into account DAM connector or standard Image Asset, as those JSON entries differ depending if DAM package is used.

**Comment by webhdx** [comment]
It's the simplest solution but we can't really ignore the root cause and rely on a workaround that only makes sure UI is not crashing. Even if the impact is minimal because corrupted data fixes itself when content is updated there is still a bug in the system that violates data integrity in the first place. I think we should attempt to fix it and provide migration script that will take care of removing broken relations in ImageAsset FT.

**Comment by barw4** [comment]
Closing as obsolete.

**Pull request closed without merging**
